name: WOG Equalizer APK Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # అప్‌డేట్ చేయబడింది (v3 నుండి v4 కి)

      - name: Setup Java
        uses: actions/setup-java@v4 # అప్‌డేట్ చేయబడింది (v3 నుండి v4 కి)
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4 # అప్‌డేట్ చేయబడింది (v3 నుండి v4 కి)
        with:
          name: WOG-Equalizer-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
